---
dependencies:
- name: "chartmuseum"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "1.1.5"
  condition: "chartmuseum.enabled"
- name: "jx"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "1.3.1116"
  alias: "gcactivities"
- name: "jx"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "1.3.1116"
  alias: "gcpods"
- name: "jx"
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "1.3.1116"
  alias: "gcpreviews"
- name: tekton
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "0.0.38"
- name: prow
  repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
  version: "0.0.679"

# - name: "jx"
#   repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
#   version: "1.3.1116"
#   condition: "controllerrole.enabled"
#   alias: "controllerrole"
# - name: "jx"
#   repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
#   version: "1.3.1116"
#   condition: "controllerworkflow.enabled"
#   alias: "controllerworkflow"
# - name: "jx"
#   repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
#   version: "1.3.1116"
#   condition: "controllerteam.enabled"
#   alias: "controllerteam"
# - name: "jx"
#   repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
#   version: "1.3.1116"
#   condition: "controllercommitstatus.enabled"
#   alias: "controllercommitstatus"
