{{- if .Values.GcsJenkinsXChartMuseumKey }}
apiVersion: v1
data:
  gcs-chartmuseum.key.json: {{ .Values.GcsJenkinsXChartMuseumKey }}
kind: Secret
metadata:
  name: gcs-jenkinsx-chartmuseum
type: Opaque
{{- end }}
